<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>RandomMoons</AssemblyName>
    <Description>A Lethal Company mod that lets you travel to random moons.</Description>
    <Version>1.0.5</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>C:\Users\hjone\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Testing Mods\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="LethalAPI.Terminal">
      <HintPath>..\..\..\..\DEPENDENCIES\LethalAPI.Terminal.dll</HintPath>
    </Reference>
    <Reference Include="LethalConfig">
      <HintPath>..\..\..\..\DEPENDENCIES\LethalConfig.dll</HintPath>
    </Reference>
	<Reference Include="CSync">
		<HintPath>..\..\..\..\DEPENDENCIES\CSync.dll</HintPath>
	</Reference>
	<Reference Include="HarmonyLib">
		<HintPath>C:\Users\hjone\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Testing Mods\BepInEx\core\0Harmony.dll</HintPath>
	</Reference>
    <Reference Include="Unity.Collections">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\Unity.Netcode.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\Lethal Company_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
